insert into ITEM (name, description, availability, cost, legality) values ('item1', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 8, 81, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item2', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 4, 5, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item3', 'Maecenas rhoncus aliquam lacus.', 5, 3, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item4', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 5, 29, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item5', 'Nullam varius.', 9, 13, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item6', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 5, 30, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item7', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 1, 97, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item8', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, 95, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item9', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 7, 19, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item10', 'Vestibulum sed magna at nunc commodo placerat.', 9, 70, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item11', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 2, 52, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item12', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 2, 94, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item13', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 4, 19, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item14', 'Maecenas ut massa quis augue luctus tincidunt.', 5, 52, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item15', 'Morbi vel lectus in quam fringilla rhoncus.', 10, 73, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item16', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 6, 38, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item17', 'Morbi quis tortor id nulla ultrices aliquet.', 5, 58, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item18', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 3, 82, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item19', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 3, 14, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item20', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 3, 37, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item21', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 88, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item22', 'Morbi a ipsum. Integer a nibh. In quis justo.', 8, 21, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item23', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 5, 20, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item24', 'Quisque ut erat. Curabitur gravida nisi at nibh.', 1, 4, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item25', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 5, 87, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item26', 'Aenean auctor gravida sem.', 4, 90, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item27', 'In sagittis dui vel nisl.', 10, 99, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item28', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 10, 6, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item29', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 9, 2, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item30', 'Nunc nisl.', 10, 8, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item31', 'Duis consequat dui nec nisi volutpat eleifend.', 7, 40, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item32', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 10, 100, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item33', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 8, 84, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item34', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 6, 99, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item35', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 3, 96, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item36', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 4, 57, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item37', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 10, 70, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item38', 'Etiam justo.', 4, 24, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item39', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 8, 88, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item40', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 10, 79, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item41', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 5, 1, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item42', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 1, 33, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item43', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 10, 35, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item44', 'In quis justo. Maecenas rhoncus aliquam lacus.', 8, 45, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item45', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 2, 67, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item46', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 10, 83, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item47', 'Nam tristique tortor eu pede.', 8, 90, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item48', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 4, 82, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item49', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 6, 97, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item50', 'Proin eu mi.', 8, 36, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item51', 'Quisque ut erat. Curabitur gravida nisi at nibh.', 7, 29, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item52', 'Suspendisse ornare consequat lectus.', 8, 71, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item53', 'In eleifend quam a odio.', 5, 4, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item54', 'In quis justo. Maecenas rhoncus aliquam lacus.', 10, 77, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item55', 'Praesent blandit.', 9, 15, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item56', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 4, 63, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item57', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 1, 91, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item58', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 4, 73, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item59', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 2, 95, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item60', 'Nulla nisl.', 5, 38, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item61', 'Suspendisse potenti. Nullam porttitor lacus at turpis.', 2, 31, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item62', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 8, 48, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item63', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 6, 25, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item64', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 7, 74, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item65', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 9, 81, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item66', 'Nulla ac enim.', 7, 69, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item67', 'Quisque id justo sit amet sapien dignissim vestibulum.', 1, 48, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item68', 'Etiam pretium iaculis justo.', 6, 40, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item69', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 3, 78, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item70', 'Ut tellus.', 9, 61, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item71', 'Cras non velit nec nisi vulputate nonummy.', 7, 42, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item72', 'Nulla nisl. Nunc nisl.', 3, 88, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item73', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 1, 66, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item74', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 2, 79, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item75', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 8, 42, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item76', 'Pellentesque ultrices mattis odio.', 9, 30, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item77', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 5, 96, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item78', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 1, 78, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item79', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 3, 11, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item80', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 3, 77, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item81', 'Maecenas pulvinar lobortis est.', 10, 46, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item82', 'Duis consequat dui nec nisi volutpat eleifend.', 3, 44, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item83', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 9, 71, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item84', 'Curabitur at ipsum ac tellus semper interdum.', 1, 21, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item85', 'Nulla ac enim.', 3, 65, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item86', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 1, 12, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item87', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 6, 56, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item88', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4, 40, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item89', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 4, 8, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item90', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 4, 97, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item91', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 6, 4, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item92', 'Vivamus vel nulla eget eros elementum pellentesque.', 8, 74, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item93', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 9, 9, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item94', 'Duis bibendum.', 10, 69, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item95', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 6, 2, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item96', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 9, 68, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item97', 'Nunc rhoncus dui vel sem. Sed sagittis.', 2, 82, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item98', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 2, 90, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item99', 'Suspendisse potenti.', 7, 48, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item100', 'Praesent blandit lacinia erat.', 7, 40, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item101', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 8, 87, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item102', 'Aliquam quis turpis eget elit sodales scelerisque.', 3, 89, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item103', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 4, 78, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item104', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 2, 72, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item105', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 10, 36, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item106', 'Integer ac neque.', 9, 84, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item107', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4, 85, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item108', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 9, 42, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item109', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 1, 85, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item110', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 6, 48, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item111', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 3, 25, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item112', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 3, 25, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item113', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 8, 80, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item114', 'Proin at turpis a pede posuere nonummy.', 3, 71, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item115', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 2, 95, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item116', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', 10, 35, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item117', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 3, 63, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item118', 'In congue. Etiam justo.', 3, 19, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item119', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 2, 11, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item120', 'Suspendisse potenti.', 2, 71, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item121', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 6, 3, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item122', 'Donec semper sapien a libero.', 6, 54, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item123', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 6, 2, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item124', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 5, 60, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item125', 'In hac habitasse platea dictumst.', 4, 74, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item126', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 2, 43, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item127', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 1, 74, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item128', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 3, 12, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item129', 'Suspendisse ornare consequat lectus.', 3, 99, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item130', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 6, 92, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item131', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 6, 55, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item132', 'Integer ac neque.', 5, 94, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item133', 'Aenean sit amet justo.', 2, 27, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item134', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 8, 9, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item135', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, 80, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item136', 'Donec quis orci eget orci vehicula condimentum.', 3, 29, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item137', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 1, 82, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item138', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, 16, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item139', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 10, 80, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item140', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 6, 12, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item141', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 3, 8, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item142', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 8, 22, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item143', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 6, 67, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item144', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 1, 85, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item145', 'Proin risus.', 7, 56, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item146', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 9, 66, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item147', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 2, 27, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item148', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 8, 63, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item149', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 2, 29, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item150', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 3, 23, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item151', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 6, 13, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item152', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 10, 87, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item153', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 9, 60, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item154', 'Morbi non quam nec dui luctus rutrum.', 5, 9, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item155', 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 10, 41, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item156', 'Morbi quis tortor id nulla ultrices aliquet.', 6, 90, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item157', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 9, 47, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item158', 'Vestibulum ac est lacinia nisi venenatis tristique.', 3, 4, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item159', 'Mauris lacinia sapien quis libero.', 1, 32, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item160', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 4, 21, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item161', 'Quisque porta volutpat erat.', 3, 5, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item162', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 6, 77, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item163', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 98, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item164', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 9, 27, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item165', 'Nunc rhoncus dui vel sem. Sed sagittis.', 6, 40, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item166', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 5, 46, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item167', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 3, 56, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item168', 'Praesent blandit.', 1, 38, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item169', 'Nullam varius.', 6, 52, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item170', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 9, 28, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item171', 'Aliquam non mauris. Morbi non lectus.', 2, 31, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item172', 'Etiam vel augue. Vestibulum rutrum rutrum neque.', 5, 57, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item173', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 10, 16, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item174', 'Duis consequat dui nec nisi volutpat eleifend.', 2, 88, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item175', 'Suspendisse accumsan tortor quis turpis.', 7, 50, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item176', 'Vivamus tortor. Duis mattis egestas metus.', 6, 84, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item177', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 3, 32, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item178', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 5, 59, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item179', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 2, 21, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item180', 'Nam nulla.', 8, 95, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item181', 'Vivamus tortor.', 9, 34, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item182', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 8, 70, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item183', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 7, 29, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item184', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3, 77, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item185', 'Donec semper sapien a libero. Nam dui.', 2, 5, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item186', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 8, 21, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item187', 'Donec vitae nisi.', 9, 61, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item188', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 1, 5, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item189', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 5, 7, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item190', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 7, 86, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item191', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 8, 76, 'F');
insert into ITEM (name, description, availability, cost, legality) values ('item192', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 1, 55, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item193', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2, 93, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item194', 'Nulla justo.', 5, 89, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item195', 'Morbi a ipsum.', 8, 29, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item196', 'Maecenas ut massa quis augue luctus tincidunt.', 7, 44, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item197', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 1, 3, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item198', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 4, 64, 'R');
insert into ITEM (name, description, availability, cost, legality) values ('item199', 'In hac habitasse platea dictumst.', 8, 35, 'L');
insert into ITEM (name, description, availability, cost, legality) values ('item200', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 5, 21, 'L');
